export const DIGILOCKER_TOKEN_URL = 'https://api.digitallocker.gov.in/public/oauth2/1/token'
export const DIGILOCKER_AADHAAR = 'https://api.digitallocker.gov.in/public/oauth2/3/xml/eaadhaar'
export const DIGILOCKER_ISSUE_DOCUMENT = 'https://api.digitallocker.gov.in/public/oauth2/2/files/issued'
export const DIGILOCKER_FETCH_DOCUMENT = 'https://api.digitallocker.gov.in/public/oauth2/1/xml/'
export const DIGILOCKER_FETCH_FILE = 'https://api.digitallocker.gov.in/public/oauth2/1/file/'
export const DIGILOCKER_CLIENT_ID_URL_1 =
  'https://api.digitallocker.gov.in/public/oauth2/1/authorize?response_type=code&client_id='
export const DIGILOCKER_REDIRECT_URL_2 = '&redirect_uri='
export const DIGILOCKER_CODE_CHALLENGE_URL_3 = '&state=adeya2024&code_challenge='
export const DIGILOCKER_CODE_CHALLENGE_METHOD_URL_4 = '&code_challenge_method=S256'
