name: 'Pipeline'

on:
  push:
    branches: ['main']

  pull_request:
    types: [opened, synchronize]

jobs:
  continous-integration:
    name: 'Continuous Integration'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm check-format

      - name: Check types
        run: pnpm check-types

      - name: Test
        run: pnpm test
